#define TK_OPTION                          1
#define TK_ASSIGN                          2
#define TK_DELIM                           3
#define TK_PACKAGE                         4
#define TK_LBRACE                          5
#define TK_RBRACE                          6
#define TK_ENUM                            7
#define TK_STRUCT                          8
#define TK_LSBRACKET                       9
#define TK_RSBRACKET                      10
#define TK_COMMA                          11
#define TK_REQUIRED                       12
#define TK_OPTIONAL                       13
#define TK_REPEATED                       14
#define TK_ORDERMAP                       15
#define TK_INTEGER                        16
#define TK_SINTEGER                       17
#define TK_UINTEGER                       18
#define TK_INTEGER64                      19
#define TK_SINTEGER64                     20
#define TK_UINTEGER64                     21
#define TK_FLOAT                          22
#define TK_DOUBLE                         23
#define TK_STRING                         24
#define TK_BOOL                           25
#define TK_DEFAULT                        26
#define TK_PACKED                         27
#define TK_COMMENT                        28
#define TK_CUSTOM                         29
